main/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reserva.urls')),
    path('',include('stand.urls')),
]

reserva/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index.as_view(), name='index'),
    path('listar/', views.listReserva.as_view(), name ="listar"),
    path('criar/', views.Criar.as_view(), name ="criar"),
    path('update/<int:pk>/', views.ReservaUpdateView.as_view(), name ="update"),
    path('delete/<int:pk>/', views.Delete.as_view(), name ="delete"),
     path('detalhe/<int:pk>/', views.ReservaDetalhe.as_view(), name='detalhe'),


]

stand/urls.py
from django.urls import path
from . import views
app_name = "stand"
urlpatterns = [
 
    path('listarStand/', views.listStand.as_view(), name ="listarStand"),
    path('criarStand/', views.CriarStand.as_view(), name ="criarStand"),
    path('updateStand/<int:pk>/', views.StandUpdateView.as_view(), name ="updateStand"),
    path('deleteStand/<int:pk>/', views.Delete.as_view(), name ="deleteStand"),
     path('detalheStand/<int:pk>/', views.StandDetalhe.as_view(), name='detalheStand'),


]

reserva/models.py
from django.db import models

# Create your models here.
class Stand(models.Model):
    localizacao = models.CharField(max_length=200)
    valor = models.DecimalField(
    verbose_name=("Valor"),
    decimal_places=2,
    max_digits=6
)


    def __str__(self):
        return self.localizacao

class Reserva(models.Model):
    cnpj=models.CharField(max_length=200)
    nome_empresa=models.CharField(max_length=200)
    categoria_empresa=models.CharField(max_length=200)
    quitado=models.BooleanField()
    stand=models.ForeignKey(Stand,on_delete=models.CASCADE)

    def __str__(self):
        return self.nome_empresa

stand/models.py
from django.db import models

# Create your models here.

reserva/views.py
from django.shortcuts import render,get_object_or_404, redirect
from reserva.models import Reserva,Stand
from django.views.generic import ListView,CreateView,DeleteView,DetailView, UpdateView,TemplateView
from reserva.form import ReservaForm
from django.urls import reverse_lazy
from django.contrib.messages import views


#VIEWS COM CBV

class index(TemplateView):
    template_name = "core/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_reservas'] = Reserva.objects.count()
        context['total_stands'] = Stand.objects.count()
        return context



class listReserva(ListView):
    template_name = 'core/listaReserva.html'
    model = Reserva
    context_object_name = 'reserva'
    paginate_by = 2



#criar
class Criar(views.SuccessMessageMixin,CreateView):

    form_class = ReservaForm
    template_name = 'core/formReserva.html'
    success_url = reverse_lazy('listar')
    success_message = "Reserva criada com sucesso!"


class Delete(views.SuccessMessageMixin,DeleteView):
    model = Reserva
    template_name = 'core/confirm.html'
    success_url = reverse_lazy("listar")
    context_object_name= "reserva"
    success_message = "Reserva deletada com sucesso!"




class ReservaUpdateView(views.SuccessMessageMixin,UpdateView):
  model = Reserva
  form_class = ReservaForm
  success_url = reverse_lazy("listar")
  template_name = "core/formReserva.html"
  success_message = "Reserva atualizada com sucesso!"


class ReservaDetalhe(DetailView):
    model = Reserva
    template_name = "core/detalheReserva.html"

stand/views.py
from django.shortcuts import render,get_object_or_404, redirect
from reserva.models import Stand
from django.views.generic import ListView,CreateView,DeleteView,DetailView, UpdateView,TemplateView
from stand.form import StandForm
from django.urls import reverse_lazy
from django.contrib.messages import views


#---------------------VIEWS COM CBV------------------------------------




class listStand(ListView):
   
    template_name ='stand/listarStand.html'
    model = Stand
    context_object_name = 'stand'
    paginate_by = 2



#criar
class CriarStand(views.SuccessMessageMixin,CreateView):

    form_class = StandForm
    template_name = 'stand/formStand.html'
    success_url = reverse_lazy('stand:listarStand')
    success_message = "Stand criado com sucesso!"


class Delete(views.SuccessMessageMixin,DeleteView):
    model = Stand
    template_name = 'stand/confirmStand.html'
    success_url = reverse_lazy("stand:listarStand")
    context_object_name= "stand"
    success_message = "Stand deletado com sucesso!"



class StandUpdateView(views.SuccessMessageMixin,UpdateView):
  model = Stand
  form_class = StandForm
  success_url = reverse_lazy("stand:listarStand")
  template_name = "stand/formStand.html"
  success_message = "Stand atualizado com sucesso!"


class StandDetalhe(DetailView):
    model = Stand
    template_name = "stand/detalheStand.html"

reserva/templates/core/confirm.html
{%extends 'base.html'%}


{% block content %}
<div class="container mt-5">
    <h2 class="text-center alert alert-danger">
         Delete Reserva
    </h2>

    <div class="row">
        <div class="col-md">
           <form method="POST"> 
            {% csrf_token%}
            <h5>Tem certeza que deseja deletar a reserva {{reserva}}?</h5>
            
            <input class="btn btn-danger" type="submit" value="Sim">
           
          
            <a href="/listar" class="btn btn-secondary">Voltar</a>
           
           </form>
        </div>
    </div>
</div>

{% endblock content %}

reserva/templates/core/detalheReserva.html
{% extends "base.html" %}

{% block title %}
Detalhes das Reservas
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <h1 class="display-4">Detalhe das Reservas</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">CNPJ</h5>
            <p class="card-text">{{reserva.cnpj}}</p>

            <h5 class="card-title">Nome da empresa</h5>
            <p class="card-text">{{reserva.nome_empresa}}</p>

            <h5 class="card-title">Categoria da empresa</h5>
            <p class="card-text">{{reserva.categoria_empresa}}</p>
           
            <h5 class="card-title">Esta quitado?</h5>
            {% if reserva.quitado %}
            <p class="card-text">Pago</p>
            {% else%}
            <p class="card-text">Pendente</p>
            {% endif %}

            <h5 class="card-title">Stand</h5>
            <p class="card-text">{{reserva.stand}}</p>
         
        </div>
      
        
    </div>
    <a href="/listar" class="btn btn-secondary">Voltar</a>
{% endblock %}

reserva/templates/core/formReserva.html
{% extends "base.html" %}

{% block title %}Forms{% endblock %}

{% block content %}
<div class="mt-5">

    <h2>Formulário</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="exampleInputPassword1">CNPJ</label>

            {{form.cnpj}}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Nome da empresa:</label>

            {{form.nome_empresa}}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Categoria da empresa:</label>

            {{form.categoria_empresa}}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Quitado:</label>

            {{form.quitado}}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Stand:</label>

            {{form.stand}}
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>
      
         <a class='btn btn-secondary' href='/listar'> Voltar </a>
    </form>
</div>
{% endblock %}

reserva/templates/core/index.html
{% extends "base.html" %}


{% block content %}
<div class="row mt-3">
    <div class="col-md-4">
      <div class="card text-white bg-primary mb-3">
        <div class="card-header">Reservas</div>
        <div class="card-body">
          <h5 class="card-title">Total de Reservas</h5>
          <p class="card-text">{{ total_reservas }}</p> <!-- Substitua pelo valor real -->
        </div>
      </div>
    </div>

    
  <div class="col-md-4">
    <div class="card text-white bg-success mb-3">
      <div class="card-header">Stands</div>
      <div class="card-body">
        <h5 class="card-title">Total de stands</h5>
        <p class="card-text">{{ total_stands }}</p> <!-- Substitua pelo valor real -->
      </div>
    </div>
  </div>



{% endblock %}

reserva/templates/core/listaReserva.html
{% extends "base.html" %}


{% block title %}Listas{% endblock %}

{% block content %}





<div class="mt-5">


    
    <h2>Lista de Reservas</h2>

    <table class="table">
        <thead class="thead-light">
            <tr>
             
                <th scope="col">CNPJ</th>
                <th scope="col">Nome da empresa</th>
                <th scope="col">Categoria da empresa</th>
                <th scope="col">Opções</th>

            </tr>
        </thead>
        <tbody>



            {% for x in reserva %}
            <tr>
               
                <td>{{x.cnpj}} </td>
                <td>{{x.nome_empresa}} </td>
                <td>{{x.categoria_empresa}} </td>

                <td>
                    <a href="{% url 'update' x.pk %}"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'delete' x.pk %}"><i class="fas fa-trash-alt"></i></a>
                    <a href="{% url 'detalhe' x.pk %}"><i class="fas fa-search"></i></a>
                </td>

                
            


            </tr>
           
                {%empty%}
                <p>Nenhuma reserva cadastrada</p>
            
            {% endfor %}
        </tbody>

        
      


        
</div>



        <div class="mb-3">
            <a href="{% url 'criar' %}" class="btn btn-primary">Adicionar Novo</a>
        </div>


<!--           MENSAGEM                  -->
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">
            
                {{ message }}
            </div>
            
            </div>
            {% endfor %}
        {% endif %}

<!--       FIM MENSAGEM                        -->

<div class="container text-center">
    <div class="row">
      <div class="col">
      </div>
  
      <div class="col">
  
  <!-- pagination.html -->
  <div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3">
    <nav class="w-full sm:w-auto sm:mr-auto">
      <ul class="pagination">
  
        <!-- Início da paginação -->
  
        <!-- Primeira página -->
        {% if page_obj.number != 1 %}
          <li class="page-item">
            <a class="page-link" href="?page=1&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-left" class="lucide lucide-chevrons-left w-4 h-4" data-lucide="chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- Página anterior -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-left" class="lucide lucide-chevron-left w-4 h-4" data-lucide="chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- ... -->
        <!-- {% if page_obj.number != 1 %}
          <li class="page-item"> <a class="page-link" href="#">...</a> </li>
        {% endif %} -->
  
        <!-- Páginas do meio -->
        {% for pg in page_obj.paginator.page_range %}
          <!-- Sempre mostra as 2 primeiras e 2 últimas páginas -->
          {% if pg == 1 or pg == 2 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' %}
  
            <li class="page-item {% if page_obj.number == pg %}active{% endif %}"> <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a> </li>
  
          {% else %}
  
            {% if page_obj.number == pg %}
              <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
              <!-- Mostra 2 páginas antes e 2 páginas depois da atual -->
              <li class="page-item"><a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a></li>
            {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
              <li class="page-item"> <a class="page-link" href="#">...</a> </li>
            {% endif %}
  
          {% endif %}
        {% endfor %}
  
        <!-- Próxima página -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-right" class="lucide lucide-chevron-right w-4 h-4" data-lucide="chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- Última página -->
        {% if page_obj.number != page_obj.paginator.num_pages %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-right" class="lucide lucide-chevrons-right w-4 h-4" data-lucide="chevrons-right"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg> </a>
          </li>
        {% endif %}
        <!-- Fim da paginação -->
  
      </ul>
    </nav>
  </div>
  
      </div>
  
      <div class="col">
      </div>
    </div>
  </div>
      
{% endblock %}

stand/templates/stand/confirmStand.html
{%extends 'base.html'%}


{% block content %}
<div class="container mt-5">
    <h2 class="text-center alert alert-danger">
         Delete Stand
    </h2>

    <div class="row">
        <div class="col-md">
           <form method="POST"> 
            {% csrf_token%}
            <h5>Tem certeza que deseja deletar o Stand {{stand}}?</h5>
            
            <input class="btn btn-danger" type="submit" value="Sim">
           
          
            <a href="/listarStand" class="btn btn-secondary">Voltar</a>
           
           </form>
        </div>
    </div>
</div>

{% endblock content %}

stand/templates/stand/detalheStand.html
{% extends "base.html" %}

{% block title %}
Detalhes das Reservas
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <h1 class="display-4">Detalhe dos Stands</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Localização</h5>
            <p class="card-text">{{stand.localizacao}}</p>

            <h5 class="card-title">Valor</h5>
            <p class="card-text">{{reserva.valor}}</p>

        
        </div>
      
       
    </div>
    <a href="/listarStand" class="btn btn-secondary">Voltar</a>
{% endblock %}

stand/templates/stand/formStand.html
{% extends "base.html" %}

{% block title %}Forms{% endblock %}

{% block content %}
<div class="mt-5">

    <h2>Formulário</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="exampleInputPassword1">Localização</label>

            {{form.localizacao}}
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">Valor</label>

            {{form.valor}}
        </div>
        
        <button type="submit" class="btn btn-primary">Enviar</button>
      
         <a class='btn btn-secondary' href='/listarStand'> Voltar </a>
    </form>
</div>
{% endblock %}

stand/templates/stand/listarStand.html
{% extends "base.html" %}


{% block title %}Listas de Stands{% endblock %}

{% block content %}





<div class="mt-5">


    
    <h2>Lista de Stands</h2>

    <table class="table">
        <thead class="thead-light">
            <tr>
             
                <th scope="col">Localização</th>
                <th scope="col">Ações</th>
                

            </tr>
        </thead>
        <tbody>



            {% for x in stand %}
            <tr>
               
                <td>{{x.localizacao}} </td>
              

                <td>
                    <a href="{% url 'stand:updateStand' x.pk %}"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'stand:deleteStand' x.pk %}"><i class="fas fa-trash-alt"></i></a>
                    <a href="{% url 'stand:detalheStand' x.pk %}"><i class="fas fa-search"></i></a>
                </td>

                
            


            </tr>
           
                {%empty%}
                <p>Nenhuma Stand cadastrada</p>
            
            {% endfor %}
        </tbody>

        
      


        
</div>



        <div class="mb-3">
            <a href="{% url 'stand:criarStand' %}" class="btn btn-primary">Adicionar Novo</a>
        </div>


<!--           MENSAGEM                  -->
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary" role="alert">
            
                {{ message }}
            </div>
            
            </div>
            {% endfor %}
        {% endif %}

<!--       FIM MENSAGEM                        -->

<div class="container text-center">
    <div class="row">
      <div class="col">
      </div>
  
      <div class="col">
  
  <!-- pagination.html -->
  <div class="intro-y flex flex-wrap sm:flex-row sm:flex-nowrap items-center mt-3">
    <nav class="w-full sm:w-auto sm:mr-auto">
      <ul class="pagination">
  
        <!-- Início da paginação -->
  
        <!-- Primeira página -->
        {% if page_obj.number != 1 %}
          <li class="page-item">
            <a class="page-link" href="?page=1&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-left" class="lucide lucide-chevrons-left w-4 h-4" data-lucide="chevrons-left"><polyline points="11 17 6 12 11 7"></polyline><polyline points="18 17 13 12 18 7"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- Página anterior -->
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-left" class="lucide lucide-chevron-left w-4 h-4" data-lucide="chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- ... -->
        <!-- {% if page_obj.number != 1 %}
          <li class="page-item"> <a class="page-link" href="#">...</a> </li>
        {% endif %} -->
  
        <!-- Páginas do meio -->
        {% for pg in page_obj.paginator.page_range %}
          <!-- Sempre mostra as 2 primeiras e 2 últimas páginas -->
          {% if pg == 1 or pg == 2 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' %}
  
            <li class="page-item {% if page_obj.number == pg %}active{% endif %}"> <a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a> </li>
  
          {% else %}
  
            {% if page_obj.number == pg %}
              <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
            {% elif pg > page_obj.number|add:'-3' and pg < page_obj.number|add:'3' %}
              <!-- Mostra 2 páginas antes e 2 páginas depois da atual -->
              <li class="page-item"><a class="page-link" href="?page={{ pg }}&search={{ request.GET.search }}">{{ pg }}</a></li>
            {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
              <li class="page-item"> <a class="page-link" href="#">...</a> </li>
            {% endif %}
  
          {% endif %}
        {% endfor %}
  
        <!-- Próxima página -->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevron-right" class="lucide lucide-chevron-right w-4 h-4" data-lucide="chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg> </a>
          </li>
        {% endif %}
  
        <!-- Última página -->
        {% if page_obj.number != page_obj.paginator.num_pages %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" icon-name="chevrons-right" class="lucide lucide-chevrons-right w-4 h-4" data-lucide="chevrons-right"><polyline points="13 17 18 12 13 7"></polyline><polyline points="6 17 11 12 6 7"></polyline></svg> </a>
          </li>
        {% endif %}
        <!-- Fim da paginação -->
  
      </ul>
    </nav>
  </div>
  
      </div>
  
      <div class="col">
      </div>
    </div>
  </div>
      
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Meu Projeto Django{% endblock %}</title>

    <!-- Adicione os links para os estilos do Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
   
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Página Inicial</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'listar'%}">Reservas</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'stand:listarStand'%}">Stands</a>
                </li>
            
                <li class="nav-item">
                    <a class="nav-link" href="#">Sobre</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        <!-- O conteúdo específico da página será inserido aqui pelos templates filhos -->
        {% endblock %}
    </div>


    <!-- Adicione os scripts do Bootstrap (jQuery e Popper.js) e Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>